INSERT INTO MEMBER (MEMBER_IDX, MEMBER_ID, PASSWORD, MEMBER_NAME) VALUES (1, 'user1', '$2a$10$lK6fg0nyxXerBvHgN7HWneK.GFbZIlsqy0V7eq3rbhdxuLcJB8Px2', 'user1');
INSERT INTO MEMBER (MEMBER_IDX, MEMBER_ID, PASSWORD, MEMBER_NAME) VALUES (2, 'user2', '$2a$10$w7T00ZGHtDuvI9us01bm9O/BRIYgRrmmFGEjTOJe/GWzVGNkpleBi', 'user2');
