INSERT INTO MEMBER (MEMBER_IDX, MEMBER_ID, PASSWORD, MEMBER_NAME, ACTIVATED) VALUES (1, 'user1', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'user1', 1);
INSERT INTO MEMBER (MEMBER_IDX, MEMBER_ID, PASSWORD, MEMBER_NAME, ACTIVATED) VALUES (2, 'user2', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user2', 1);

-- INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_MEMBER');
-- INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

-- INSERT INTO MEMBER_AUTHORITY (MEMBER_IDX, AUTHORITY_NAME) values (1, 'ROLE_MEMBER');
-- INSERT INTO MEMBER_AUTHORITY (MEMBER_IDX, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
-- INSERT INTO MEMBER_AUTHORITY (MEMBER_IDX, AUTHORITY_NAME) values (2, 'ROLE_MEMBER');