INSERT INTO MEMBER (MEMBER_IDX, MEMBER_ID, PASSWORD, MEMBER_NAME) VALUES (1, 'user1', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'user1');
INSERT INTO MEMBER (MEMBER_IDX, MEMBER_ID, PASSWORD, MEMBER_NAME) VALUES (2, 'user2', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user2');
